name: todo_with_firebase_auth
description: Todo App with Firebase Auth

version: 1.0.0+1

environment:
  sdk: '>=3.1.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  firebase_core: ^2.15.1
  shimmer: ^3.0.0
  google_fonts: ^5.1.0
  firebase_auth: ^4.9.0
  equatable: ^2.0.5
  bloc: ^8.1.2
  flutter_bloc: ^8.1.3
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  lottie: ^2.6.0
  rive: ^0.11.16
  sqflite: ^2.3.0
  firebase_storage: ^11.2.6

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:

  uses-material-design: true

  assets:
    - assets/images/
    - assets/lotties/